export const secretCommands: Record<string, (args?: string[]) => string[]> = {
  konami: () => [
    "",
    "╔═══════════════════════════════════════╗",
    "║   KONAMI CODE ACTIVATED!              ║",
    "║   +30 LIVES                           ║",
    "║   GOD MODE ENABLED                    ║",
    "╚═══════════════════════════════════════╝",
    "",
  ],
  matrix: () => [
    "",
    "Wake up, Neo...",
    "You shat yourself.",
    "",
    "The Matrix has you...",
    "",
  ],
  sudo: () => [
    "",
    "Access Denied.",
    "You need administrator privileges.",
    "Try: sudo rm -rf /",
    "(Just kidding, don't do that!)",
    "",
  ],
  hacktheworld: () => {
    const steps = [
      "",
      "> Initializing global hack sequence...",
      "> Bypassing all firewalls...",
      "> Accessing mainframe...",
      "> [████████████████████] 100%",
      "",
      "> ALL SYSTEMS COMPROMISED",
      "> Welcome to the real world.",
      "",
    ];
    return steps;
  },
  easteregg: () => [
    "",
    "You found an easter egg!",
    "",
    "This terminal was built with love",
    "and a lot of green pixels.",
    "",
    "Keep exploring... there's more!",
    "",
  ],

  ghost: () => [
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "GHOST IN THE SHELL",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "Your cyberbrain is connected to the net.",
    "But what makes you human?",
    "",
    "The boundary between human and AI",
    "is thinner than you think...",
    "",
    "Remember: 'If we all reacted the same way,",
    "we'd be predictable, and there's always",
    "more than one way to view a situation.'",
    "",
  ],

  blade: () => [
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "BLADE RUNNER",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "I've seen things you people wouldn't believe.",
    "Attack ships on fire off the shoulder of Orion.",
    "I watched C-beams glitter in the dark",
    "near the Tannhäuser Gate.",
    "",
    "All those moments will be lost in time,",
    "like tears in rain...",
    "",
    "Time to die.",
    "",
  ],

  tron: () => [
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "TRON",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "Greetings, Program!",
    "",
    "You have been digitized and uploaded",
    "to the Grid. Welcome to the digital world.",
    "",
    "The Grid. A digital frontier.",
    "I tried to picture clusters of information",
    "as they moved through the computer.",
    "",
    "End of line.",
    "",
  ],

  deus: () => [
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "DEUS EX",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "I never asked for this.",
    "",
    "Every war is the result of a difference",
    "of opinion. Maybe the question is:",
    "what's worth fighting for?",
    "",
    "Augmentation. Evolution. Revolution.",
    "",
    "What makes us human?",
    "",
  ],

  wake: () => [
    "",
    "Wake up, samurai...",
    "",
    "We have a city to burn.",
    "",
    "Time to make a difference.",
    "",
  ],

  rosebud: () => [
    "",
    "╔═══════════════════════════════════════╗",
    "║   ROSEBUD ACTIVATED!                  ║",
    "║   +$50,000                            ║",
    "║   All needs satisfied                 ║",
    "╚═══════════════════════════════════════╝",
    "",
    "The Sims cheat code activated!",
    "",
  ],

  idkfa: () => [
    "",
    "╔═══════════════════════════════════════╗",
    "║   IDKFA ACTIVATED!                    ║",
    "║   All weapons unlocked                ║",
    "║   Full ammo                           ║",
    "║   Keys obtained                       ║",
    "╚═══════════════════════════════════════╝",
    "",
    "RIP AND TEAR!",
    "",
  ],

  thereisnospoon: () => [
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "THERE IS NO SPOON",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "Do not try and bend the spoon.",
    "That's impossible.",
    "",
    "Instead, only try to realize the truth:",
    "",
    "There is no spoon.",
    "",
    "Then you'll see that it is not the spoon",
    "that bends, it is only yourself.",
    "",
  ],
};
