export const getDestroyOutput = (): string[] => {
  return [
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "CRITICAL WARNING: DANGEROUS COMMAND DETECTED",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> Command: sudo rm -rf /",
    "> This will DELETE EVERYTHING on the system!",
    "> Proceeding with destruction sequence...",
    "",
    "> [1/10] Initializing recursive deletion...",
    "> [2/10] Bypassing safety checks...",
    "> [3/10] Escalating privileges...",
    "> [4/10] Starting file system destruction...",
    "",
    "rm: cannot remove '/proc/kmsg': Operation not permitted",
    "rm: cannot remove '/proc/sysrq-trigger': Operation not permitted",
    "rm: cannot remove '/proc/meminfo': Operation not permitted",
    "rm: cannot remove '/proc/cpuinfo': Operation not permitted",
    "rm: cannot remove '/sys/kernel': Operation not permitted",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /bin/ - Core System Binaries",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /bin/bash (1.2 MB) [DELETED]",
    "> /bin/sh (856 KB) [DELETED]",
    "> /bin/dash (234 KB) [DELETED]",
    "> /bin/ls (45 KB) [DELETED]",
    "> /bin/cat (32 KB) [DELETED]",
    "> /bin/rm (48 KB) [DELETED]",
    "> /bin/mkdir (42 KB) [DELETED]",
    "> /bin/cp (52 KB) [DELETED]",
    "> /bin/mv (44 KB) [DELETED]",
    "> /bin/chmod (38 KB) [DELETED]",
    "> /bin/chown (41 KB) [DELETED]",
    "> /bin/sudo (156 KB) [DELETED]",
    "> /bin/grep (67 KB) [DELETED]",
    "> /bin/find (89 KB) [DELETED]",
    "> /bin/sed (45 KB) [DELETED]",
    "> /bin/awk (234 KB) [DELETED]",
    "> /bin/tar (156 KB) [DELETED]",
    "> /bin/gzip (45 KB) [DELETED]",
    "> /bin/zip (89 KB) [DELETED]",
    "> /bin/unzip (67 KB) [DELETED]",
    "> /bin/curl (234 KB) [DELETED]",
    "> /bin/wget (189 KB) [DELETED]",
    "> /bin/ssh (456 KB) [DELETED]",
    "> /bin/scp (234 KB) [DELETED]",
    "> /bin/rsync (345 KB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /usr/bin/ - User Binaries",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /usr/bin/python3 (4.5 MB) [DELETED]",
    "> /usr/bin/python2.7 (2.1 MB) [DELETED]",
    "> /usr/bin/node (12.3 MB) [DELETED]",
    "> /usr/bin/npm (2.4 MB) [DELETED]",
    "> /usr/bin/gcc (2.1 MB) [DELETED]",
    "> /usr/bin/g++ (2.3 MB) [DELETED]",
    "> /usr/bin/make (234 KB) [DELETED]",
    "> /usr/bin/cmake (3.2 MB) [DELETED]",
    "> /usr/bin/git (3.2 MB) [DELETED]",
    "> /usr/bin/docker (45.6 MB) [DELETED]",
    "> /usr/bin/docker-compose (12.3 MB) [DELETED]",
    "> /usr/bin/kubectl (45.2 MB) [DELETED]",
    "> /usr/bin/vim (2.1 MB) [DELETED]",
    "> /usr/bin/nano (234 KB) [DELETED]",
    "> /usr/bin/emacs (12.5 MB) [DELETED]",
    "> /usr/bin/firefox (156.7 MB) [DELETED]",
    "> /usr/bin/chrome (234.5 MB) [DELETED]",
    "> /usr/bin/vscode (567.8 MB) [DELETED]",
    "> /usr/bin/mysql (45.2 MB) [DELETED]",
    "> /usr/bin/postgresql (67.8 MB) [DELETED]",
    "> /usr/bin/redis-server (12.3 MB) [DELETED]",
    "> /usr/bin/nginx (2.1 MB) [DELETED]",
    "> /usr/bin/apache2 (3.4 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /usr/lib/ - System Libraries",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /usr/lib/libc.so.6 (2.3 MB) [DELETED]",
    "> /usr/lib/libssl.so.1.1 (456 KB) [DELETED]",
    "> /usr/lib/libcrypto.so.1.1 (1.2 MB) [DELETED]",
    "> /usr/lib/libpthread.so.0 (234 KB) [DELETED]",
    "> /usr/lib/libm.so.6 (567 KB) [DELETED]",
    "> /usr/lib/libdl.so.2 (45 KB) [DELETED]",
    "> /usr/lib/libz.so.1 (89 KB) [DELETED]",
    "> /usr/lib/libbz2.so.1.0 (67 KB) [DELETED]",
    "> /usr/lib/libxml2.so.2 (1.5 MB) [DELETED]",
    "> /usr/lib/libcurl.so.4 (234 KB) [DELETED]",
    "> /usr/lib/libsqlite3.so.0 (567 KB) [DELETED]",
    "> /usr/lib/libpng16.so.16 (234 KB) [DELETED]",
    "> /usr/lib/libjpeg.so.8 (189 KB) [DELETED]",
    "> /usr/lib/libfreetype.so.6 (456 KB) [DELETED]",
    "> /usr/lib/python3.9/ (234.5 MB) [DELETED]",
    "> /usr/lib/python2.7/ (123.4 MB) [DELETED]",
    "> /usr/lib/node_modules/ (1.2 GB) [DELETED]",
    "> /usr/lib/gcc/x86_64-linux-gnu/9/ (456.7 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /usr/share/ - Shared Data",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /usr/share/man/ (1.2 GB) [DELETED]",
    "> /usr/share/doc/ (890 MB) [DELETED]",
    "> /usr/share/locale/ (234.5 MB) [DELETED]",
    "> /usr/share/icons/ (567.8 MB) [DELETED]",
    "> /usr/share/themes/ (123.4 MB) [DELETED]",
    "> /usr/share/fonts/ (234.5 MB) [DELETED]",
    "> /usr/share/applications/ (45.6 MB) [DELETED]",
    "> /usr/share/mime/ (12.3 MB) [DELETED]",
    "> /usr/share/zoneinfo/ (2.1 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /usr/local/ - Local Installations",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /usr/local/bin/ (234 MB) [DELETED]",
    "> /usr/local/lib/ (567 MB) [DELETED]",
    "> /usr/local/include/ (123 MB) [DELETED]",
    "> /usr/local/share/ (89 MB) [DELETED]",
    "> /usr/local/src/ (456 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /usr/include/ - Header Files",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /usr/include/ (156 MB) [DELETED]",
    "> /usr/include/stdio.h (12 KB) [DELETED]",
    "> /usr/include/stdlib.h (8 KB) [DELETED]",
    "> /usr/include/string.h (6 KB) [DELETED]",
    "> /usr/include/unistd.h (5 KB) [DELETED]",
    "> /usr/include/sys/ (45 MB) [DELETED]",
    "> /usr/include/linux/ (34 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /etc/ - Configuration Files",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /etc/passwd (2.1 KB) [DELETED]",
    "> /etc/shadow (1.8 KB) [DELETED]",
    "> /etc/group (856 B) [DELETED]",
    "> /etc/gshadow (1.2 KB) [DELETED]",
    "> /etc/hosts (856 B) [DELETED]",
    "> /etc/hostname (12 B) [DELETED]",
    "> /etc/fstab (1.2 KB) [DELETED]",
    "> /etc/mtab (234 B) [DELETED]",
    "> /etc/resolv.conf (456 B) [DELETED]",
    "> /etc/network/interfaces (3.4 KB) [DELETED]",
    "> /etc/ssh/sshd_config (4.2 KB) [DELETED]",
    "> /etc/ssh/ssh_config (2.1 KB) [DELETED]",
    "> /etc/systemd/system/ (12 MB) [DELETED]",
    "> /etc/systemd/user/ (3.4 MB) [DELETED]",
    "> /etc/nginx/nginx.conf (8.7 KB) [DELETED]",
    "> /etc/nginx/sites-available/ (234 KB) [DELETED]",
    "> /etc/apache2/apache2.conf (12.3 KB) [DELETED]",
    "> /etc/mysql/my.cnf (4.5 KB) [DELETED]",
    "> /etc/postgresql/ (234 KB) [DELETED]",
    "> /etc/redis/redis.conf (2.1 KB) [DELETED]",
    "> /etc/docker/daemon.json (1.2 KB) [DELETED]",
    "> /etc/crontab (456 B) [DELETED]",
    "> /etc/cron.d/ (234 KB) [DELETED]",
    "> /etc/cron.hourly/ (12 KB) [DELETED]",
    "> /etc/cron.daily/ (45 KB) [DELETED]",
    "> /etc/cron.weekly/ (23 KB) [DELETED]",
    "> /etc/cron.monthly/ (34 KB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /home/ - User Data",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /home/user/Documents/ (2.3 GB) [DELETED]",
    "> /home/user/Downloads/ (15.6 GB) [DELETED]",
    "> /home/user/Pictures/ (8.9 GB) [DELETED]",
    "> /home/user/Videos/ (45.7 GB) [DELETED]",
    "> /home/user/Music/ (12.3 GB) [DELETED]",
    "> /home/user/Desktop/ (234 MB) [DELETED]",
    "> /home/user/Projects/ (5.6 GB) [DELETED]",
    "> /home/user/.bashrc (3.2 KB) [DELETED]",
    "> /home/user/.bash_history (234 KB) [DELETED]",
    "> /home/user/.zshrc (2.1 KB) [DELETED]",
    "> /home/user/.vimrc (1.2 KB) [DELETED]",
    "> /home/user/.gitconfig (456 B) [DELETED]",
    "> /home/user/.ssh/id_rsa (1.8 KB) [DELETED]",
    "> /home/user/.ssh/id_rsa.pub (456 B) [DELETED]",
    "> /home/user/.ssh/known_hosts (12 KB) [DELETED]",
    "> /home/user/.ssh/config (234 B) [DELETED]",
    "> /home/user/.config/ (234 MB) [DELETED]",
    "> /home/user/.cache/ (1.2 GB) [DELETED]",
    "> /home/user/.local/ (567 MB) [DELETED]",
    "> /home/user/.npm/ (123 MB) [DELETED]",
    "> /home/user/.docker/ (45 MB) [DELETED]",
    "> /home/user/.kube/ (12 MB) [DELETED]",
    "> /home/user/.aws/ (234 KB) [DELETED]",
    "> /home/user/.gnupg/ (45 KB) [DELETED]",
    "> /home/user/.mozilla/ (234 MB) [DELETED]",
    "> /home/user/.google-chrome/ (567 MB) [DELETED]",
    "> /home/user/.vscode/ (123 MB) [DELETED]",
    "> /home/user/.git/ (45 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /root/ - Root User Data",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /root/.bash_history (45 KB) [DELETED]",
    "> /root/.bashrc (2.1 KB) [DELETED]",
    "> /root/.profile (1.2 KB) [DELETED]",
    "> /root/.ssh/authorized_keys (234 B) [DELETED]",
    "> /root/.ssh/id_rsa (1.8 KB) [DELETED]",
    "> /root/.vimrc (2.1 KB) [DELETED]",
    "> /root/.gitconfig (456 B) [DELETED]",
    "> /root/.config/ (12 MB) [DELETED]",
    "> /root/.cache/ (45 MB) [DELETED]",
    "> /root/Documents/ (234 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /var/ - Variable Data",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /var/log/syslog (45 MB) [DELETED]",
    "> /var/log/auth.log (12 MB) [DELETED]",
    "> /var/log/kern.log (8.9 MB) [DELETED]",
    "> /var/log/messages (23.4 MB) [DELETED]",
    "> /var/log/daemon.log (5.6 MB) [DELETED]",
    "> /var/log/apache2/ (234 MB) [DELETED]",
    "> /var/log/nginx/ (123 MB) [DELETED]",
    "> /var/log/mysql/ (45 MB) [DELETED]",
    "> /var/log/postgresql/ (12 MB) [DELETED]",
    "> /var/log/docker/ (34 MB) [DELETED]",
    "> /var/tmp/ (234 MB) [DELETED]",
    "> /var/cache/apt/ (456 MB) [DELETED]",
    "> /var/cache/pip/ (123 MB) [DELETED]",
    "> /var/cache/npm/ (234 MB) [DELETED]",
    "> /var/lib/dpkg/ (123 MB) [DELETED]",
    "> /var/lib/mysql/ (5.6 GB) [DELETED]",
    "> /var/lib/postgresql/ (3.4 GB) [DELETED]",
    "> /var/lib/docker/ (45.6 GB) [DELETED]",
    "> /var/lib/containers/ (12.3 GB) [DELETED]",
    "> /var/lib/systemd/ (234 MB) [DELETED]",
    "> /var/lib/NetworkManager/ (45 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /opt/ - Optional Software",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /opt/google/chrome/ (234 MB) [DELETED]",
    "> /opt/vscode/ (567 MB) [DELETED]",
    "> /opt/intellij/ (1.2 GB) [DELETED]",
    "> /opt/eclipse/ (567 MB) [DELETED]",
    "> /opt/android-studio/ (2.3 GB) [DELETED]",
    "> /opt/jetbrains/ (3.4 GB) [DELETED]",
    "> /opt/nodejs/ (234 MB) [DELETED]",
    "> /opt/mongodb/ (567 MB) [DELETED]",
    "> /opt/elasticsearch/ (1.2 GB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /srv/ - Service Data",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /srv/www/ (1.2 GB) [DELETED]",
    "> /srv/git/ (567 MB) [DELETED]",
    "> /srv/docker/ (234 MB) [DELETED]",
    "> /srv/database/ (3.4 GB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /media/ & /mnt/ - Mount Points",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /media/usb0/ (8.9 GB) [DELETED]",
    "> /media/usb1/ (4.5 GB) [DELETED]",
    "> /media/cdrom/ (567 MB) [DELETED]",
    "> /mnt/backup/ (45.6 GB) [DELETED]",
    "> /mnt/storage/ (123.4 GB) [DELETED]",
    "> /mnt/nas/ (234.5 GB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /boot/ - Boot Files",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /boot/vmlinuz-5.15.0 (12 MB) [DELETED]",
    "> /boot/vmlinuz-5.16.0 (13 MB) [DELETED]",
    "> /boot/vmlinuz-5.17.0 (14 MB) [DELETED]",
    "> /boot/initrd.img-5.15.0 (45 MB) [DELETED]",
    "> /boot/initrd.img-5.16.0 (46 MB) [DELETED]",
    "> /boot/initrd.img-5.17.0 (47 MB) [DELETED]",
    "> /boot/grub/grub.cfg (8.7 KB) [DELETED]",
    "> /boot/grub/grubenv (1.2 KB) [DELETED]",
    "> /boot/efi/EFI/ (234 MB) [DELETED]",
    "> /boot/efi/EFI/BOOT/ (12 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /lib/ & /lib64/ - Libraries",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /lib/libc-2.31.so (2.1 MB) [DELETED]",
    "> /lib/libm-2.31.so (567 KB) [DELETED]",
    "> /lib/libpthread-2.31.so (234 KB) [DELETED]",
    "> /lib/libdl-2.31.so (45 KB) [DELETED]",
    "> /lib/ld-linux.so.2 (178 KB) [DELETED]",
    "> /lib64/ld-linux-x86-64.so.2 (178 KB) [DELETED]",
    "> /lib64/libc.so.6 (2.3 MB) [DELETED]",
    "> /lib32/libc.so.6 (1.8 MB) [DELETED]",
    "> /lib/x86_64-linux-gnu/ (234 MB) [DELETED]",
    "> /lib/systemd/ (45 MB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /sbin/ - System Binaries",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /sbin/init (1.5 MB) [DELETED]",
    "> /sbin/reboot (45 KB) [DELETED]",
    "> /sbin/shutdown (52 KB) [DELETED]",
    "> /sbin/ifconfig (67 KB) [DELETED]",
    "> /sbin/ip (234 KB) [DELETED]",
    "> /sbin/route (45 KB) [DELETED]",
    "> /sbin/iptables (234 KB) [DELETED]",
    "> /sbin/iptables-restore (123 KB) [DELETED]",
    "> /sbin/mount (45 KB) [DELETED]",
    "> /sbin/umount (34 KB) [DELETED]",
    "> /sbin/fdisk (234 KB) [DELETED]",
    "> /sbin/parted (567 KB) [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[DELETING] /tmp/ & /run/ - Temporary Files",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> /tmp/tmp.XXXXXX (234 KB) [DELETED]",
    "> /tmp/.X11-unix/ (12 MB) [DELETED]",
    "> /tmp/systemd-private-*/ (45 MB) [DELETED]",
    "> /run/systemd/ (12 MB) [DELETED]",
    "> /run/user/1000/ (45 MB) [DELETED]",
    "> /run/docker/ (234 MB) [DELETED]",
    "> /run/containerd/ (123 MB) [DELETED]",
    "",
    "> /lost+found/ [DELETED]",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[ERRORS] Protected System Resources",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "rm: cannot remove '/dev/null': Device or resource busy",
    "rm: cannot remove '/dev/zero': Device or resource busy",
    "rm: cannot remove '/dev/random': Device or resource busy",
    "rm: cannot remove '/dev/urandom': Device or resource busy",
    "rm: cannot remove '/dev/stdin': Device or resource busy",
    "rm: cannot remove '/dev/stdout': Device or resource busy",
    "rm: cannot remove '/dev/stderr': Device or resource busy",
    "rm: cannot remove '/proc': Operation not permitted",
    "rm: cannot remove '/sys': Operation not permitted",
    "rm: cannot remove '/dev': Operation not permitted",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[5/10] Scanning for remaining files...",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> Scanning filesystem...",
    "> Checking for hidden files...",
    "> Searching for symbolic links...",
    "> Verifying deletion...",
    "> Found 0 files remaining",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[6/10] Finalizing destruction...",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> [                    ] 0%",
    "> [██                  ] 10%",
    "> [████                ] 20%",
    "> [██████              ] 30%",
    "> [████████            ] 40%",
    "> [██████████          ] 50%",
    "> [████████████        ] 60%",
    "> [██████████████      ] 70%",
    "> [████████████████    ] 80%",
    "> [██████████████████  ] 90%",
    "> [████████████████████] 100%",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[7/10] System integrity check...",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> Checking filesystem integrity...",
    "> ERROR: Filesystem corrupted",
    "> ERROR: Cannot read superblock",
    "> ERROR: Inode table corrupted",
    "> ERROR: Directory structure destroyed",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[8/10] Network services shutdown...",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> Stopping network services...",
    "> SSH service: TERMINATED",
    "> HTTP service: TERMINATED",
    "> HTTPS service: TERMINATED",
    "> Database services: TERMINATED",
    "> Docker services: TERMINATED",
    "> All network connections: CLOSED",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[9/10] System processes termination...",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> Terminating all processes...",
    "> Process 1 (init): KILLED",
    "> Process 2 (kthreadd): KILLED",
    "> Process 3 (ksoftirqd): KILLED",
    "> All user processes: TERMINATED",
    "> All system processes: TERMINATED",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "[10/10] Final system state...",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "SYSTEM COMPLETELY DESTROYED",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> Files deleted: 8,456,789",
    "> Directories removed: 234,567",
    "> Total size freed: 456.7 GB",
    "> System libraries destroyed: 12,345",
    "> Configuration files removed: 5,678",
    "> User accounts wiped: 23",
    "> Services terminated: 156",
    "> Processes killed: 1,234",
    "",
    "> All files have been deleted.",
    "> All directories have been removed.",
    "> All system libraries have been destroyed.",
    "> All configuration files have been erased.",
    "> All user data has been wiped.",
    "> All boot files have been deleted.",
    "> All log files have been removed.",
    "> All network services have been terminated.",
    "> All system processes have been killed.",
    "",
    "> System is now completely unusable.",
    "> Recovery is impossible.",
    "> The system cannot be restored.",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "DESTRUCTION SUMMARY",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> Kernel modules: DELETED",
    "> System libraries: DELETED",
    "> Configuration files: DELETED",
    "> User data: DELETED",
    "> Boot files: DELETED",
    "> Log files: DELETED",
    "> Network services: TERMINATED",
    "> System processes: KILLED",
    "> Filesystem: CORRUPTED",
    "> Bootloader: DESTROYED",
    "> Init system: TERMINATED",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "CRITICAL ERRORS",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> ERROR: Cannot access root filesystem",
    "> ERROR: Kernel panic - not syncing",
    "> ERROR: Attempted to kill init!",
    "> ERROR: Filesystem superblock corrupted",
    "> ERROR: Cannot mount root filesystem",
    "> ERROR: No init found. Try passing init= bootarg.",
    "> ERROR: Kernel panic - Fatal exception",
    "> ERROR: System halted",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "FINAL WARNING",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "> The system has been completely destroyed.",
    "> All data has been permanently deleted.",
    "> The system cannot boot.",
    "> The system cannot be recovered.",
    "",
    "> Rebooting in 5 seconds...",
    "> 5...",
    "> 4...",
    "> 3...",
    "> 2...",
    "> 1...",
    "",
    "> SYSTEM HALTED",
    "",
  ];
};

export const createDestroyOverlay = () => {
  const overlay = document.createElement("div");
  overlay.style.cssText = `
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: #000;
    z-index: 99999;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    color: #ff0000;
    font-family: monospace;
    font-size: 32px;
    font-weight: bold;
    text-align: center;
    animation: fadeIn 0.3s, glitch 0.3s infinite;
  `;

  const style = document.createElement("style");
  style.textContent = `
    @keyframes fadeIn {
      from { opacity: 0; }
      to { opacity: 1; }
    }
    @keyframes glitch {
      0%, 100% { transform: translate(0); }
      20% { transform: translate(-2px, 2px); }
      40% { transform: translate(-2px, -2px); }
      60% { transform: translate(2px, 2px); }
      80% { transform: translate(2px, -2px); }
    }
  `;
  document.head.appendChild(style);

  overlay.innerHTML = `
    <div style="margin-bottom: 20px; text-shadow: 0 0 10px #ff0000, 0 0 20px #ff0000;">SYSTEM DESTROYED</div>
    <div style="font-size: 18px; color: #ff6666; margin-top: 10px;">All files have been deleted</div>
    <div style="font-size: 14px; color: #ff9999; margin-top: 20px;">Rebooting...</div>
  `;
  document.body.appendChild(overlay);

  let flickerCount = 0;
  const flicker = setInterval(() => {
    overlay.style.opacity = overlay.style.opacity === "0.8" ? "1" : "0.8";
    flickerCount++;
    if (flickerCount > 10) {
      clearInterval(flicker);
    }
  }, 100);

  setTimeout(() => {
    window.location.reload();
  }, 5000);
};
